# Generated by Django 5.0.6 on 2024-07-25 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhifclaim',
            name='dr_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nhifclaim',
            name='procedure',
            field=models.CharField(max_length=1000),
        ),
    ]
