# Generated by Django 5.0.6 on 2024-07-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0003_nhifclaim_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhifclaim',
            name='secondary_status',
            field=models.CharField(blank=True, choices=[('done', 'Done'), ('not_done', 'Not Done')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nhifclaim',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nhifclaim',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('declined', 'Declined'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
