# Generated by Django 5.0.6 on 2024-07-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0004_nhifclaim_secondary_status_alter_nhifclaim_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhifclaim',
            name='secondary_status',
        ),
        migrations.AddField(
            model_name='nhifclaim',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
