# Generated by Django 5.0.7 on 2024-08-19 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0008_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorgueBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type', models.CharField(choices=[('outside', 'Outside Hospital'), ('inside', 'Inside Hospital'), ('child', 'Child')], max_length=10)),
                ('body_income_date', models.DateField(default=django.utils.timezone.now)),
                ('body_release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
