# Generated by Django 5.0.7 on 2024-09-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0010_entry_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClaimNumber', models.CharField(max_length=255)),
                ('AdmissionDate', models.CharField(max_length=255)),
                ('DischargeDate', models.CharField(max_length=255)),
                ('Stage', models.CharField(max_length=255)),
                ('MemberNumber', models.CharField(max_length=255)),
                ('DependentNumber', models.CharField(max_length=255)),
                ('PatientNumber', models.CharField(max_length=255)),
                ('PatientName', models.CharField(max_length=255)),
                ('InvoiceNumber', models.CharField(max_length=255)),
                ('ExpectedClaim', models.CharField(max_length=255)),
                ('ClaimDate', models.CharField(max_length=255)),
                ('ChequeNumber', models.CharField(max_length=255)),
                ('ChequeDate', models.CharField(max_length=255)),
                ('EFTTransactionNumber', models.CharField(max_length=255)),
                ('EFTBatchNo', models.CharField(max_length=255)),
            ],
        ),
    ]
