# Generated by Django 5.0.7 on 2024-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0011_exceldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='morguebilling',
            name='age_group',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='morguebilling',
            name='body_type',
            field=models.CharField(choices=[('outside', 'Outside Hospital'), ('inside', 'Inside Hospital')], max_length=10),
        ),
    ]
