# Generated by Django 5.0.7 on 2024-10-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0012_morguebilling_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApprovedAmount', models.FloatField()),
                ('AccumulatedBill', models.FloatField()),
                ('Procedure', models.CharField(max_length=255)),
                ('ImplantCheck', models.BooleanField(default=False)),
            ],
        ),
    ]
