# Generated by Django 5.0.7 on 2024-10-11 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0013_inpatientinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('member_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RenalDialysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_admission', models.DateField(default=django.utils.timezone.now)),
                ('date_of_discharge', models.DateField(default=django.utils.timezone.now)),
                ('claim_amount', models.DecimalField(decimal_places=2, default=9500, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhif_app.patient')),
            ],
        ),
    ]
