# Generated by Django 5.0.7 on 2024-10-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0016_rename_member_number_patient_shifnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='facility_name',
            field=models.CharField(default='Our Lady Of Lourdes Mwea Hospital', max_length=100),
        ),
        migrations.AlterField(
            model_name='renaldialysisrecord',
            name='claim_amount',
            field=models.DecimalField(decimal_places=2, default=10650, max_digits=10),
        ),
    ]
