# Generated by Django 5.0.7 on 2024-11-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0017_alter_patient_facility_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shapatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inpatient_number', models.CharField(max_length=20, unique=True, verbose_name='Inpatient Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Patient Full Name')),
                ('claim_form', models.FileField(default='claim_forms/default_claim_form.pdf', upload_to='claim_forms/', verbose_name='Claim Form (PDF)')),
            ],
        ),
    ]
