# Generated by Django 5.0.7 on 2024-11-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0019_alter_shapatient_claim_form_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shapatient',
        ),
    ]
