# Generated by Django 5.0.7 on 2024-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0020_delete_shapatient'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilledForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_file', models.FileField(upload_to='filled_forms/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
