# Generated by Django 5.0.7 on 2024-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0021_filledform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilledForm',
        ),
        migrations.AddField(
            model_name='patient',
            name='claim_form',
            field=models.FileField(blank=True, null=True, upload_to='claim_forms/'),
        ),
    ]
