# Generated by Django 5.0.7 on 2024-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0022_delete_filledform_patient_claim_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preauthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('procedure', models.CharField(max_length=255)),
                ('expected_surgery_date', models.DateField()),
                ('chief_complaint', models.TextField()),
                ('vital_signs', models.TextField()),
                ('hpi', models.TextField(help_text='History of present illness')),
                ('physical_examination', models.TextField()),
                ('investigation_report_details', models.TextField()),
                ('type_of_anaesthesia', models.CharField(choices=[('general', 'General Anaesthesia'), ('local', 'Local Anaesthesia'), ('spinal', 'Spinal Block'), ('sedation', 'Sedation')], max_length=50)),
                ('is_condition_related_to_employment', models.BooleanField(default=False)),
                ('is_condition_related_to_accident', models.BooleanField(default=False)),
                ('is_patient_co_insured', models.BooleanField(default=False)),
            ],
        ),
    ]
