# Generated by Django 5.0.7 on 2024-12-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhif_app', '0023_preauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='preauthorization',
            name='doctor_name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
