# Generated by Django 5.0.7 on 2025-01-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhif_app", "0024_preauthorization_doctor_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeRecord",
            fields=[
                ("number", models.IntegerField(primary_key=True, serialize=False)),
                ("patient_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("date_of_admission", models.DateField()),
                ("date_of_discharge", models.DateField()),
                ("inpatient_number", models.CharField(max_length=20)),
                (
                    "ward_type",
                    models.CharField(
                        choices=[
                            ("ICU/HDU", "ICU/HDU"),
                            ("Medical", "Medical"),
                            ("Surgical", "Surgical"),
                            ("Amenity", "Amenity"),
                            ("Maternity", "Maternity"),
                            ("Gynecology", "Gynecology"),
                            ("Pediatrics", "Pediatrics"),
                        ],
                        max_length=20,
                    ),
                ),
                ("claim_number", models.CharField(editable=False, max_length=20)),
                ("days_spent", models.PositiveIntegerField(editable=False)),
                ("amount", models.IntegerField(default=0)),
            ],
        ),
    ]
