# Generated by Django 5.0.7 on 2025-03-13 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nhif_app", "0025_dischargerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("id_no", models.CharField(max_length=20)),
                ("doa", models.DateField()),
                ("dod", models.DateField(blank=True, null=True)),
                ("diagnosis", models.TextField()),
                ("procedure_plan", models.TextField()),
                ("mobile_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="DailyTally",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("admissions", models.IntegerField()),
                ("discharges", models.IntegerField()),
                ("surgeries", models.IntegerField()),
                ("deliveries", models.IntegerField()),
                ("radiology", models.IntegerField()),
                ("referrals_in", models.IntegerField()),
                ("referrals_out", models.IntegerField()),
            ],
        ),
    ]
